In [1]:
import torch

In [2]:
scaler=torch.tensor(6)
scaler,scaler.ndim,scaler.item() #ndim is a build in function in pytorch return tensor's dimension


(tensor(6), 0, 6)

In [3]:
#create vector of tensor
vector=torch.tensor([1,2])
vector,vector.ndim,vector.shape #item run in scaler only

(tensor([1, 2]), 1, torch.Size([2]))

In [4]:
#matrix
matrix=torch.tensor([[1,2],[3,4]])
matrix,matrix.shape,matrix.ndim

(tensor([[1, 2],
         [3, 4]]),
 torch.Size([2, 2]),
 2)

In [5]:
#higher order dimension
d3_tensor=torch.tensor([[[1,2,3],
 [4,5,6],
  [7,8,9]]])
d3_tensor,d3_tensor.shape,d3_tensor.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [6]:
#create a random tensor
random_tensor=torch.rand(size=(4,4))
print(random_tensor)
random_tensor.dtype

tensor([[0.9218, 0.9103, 0.2954, 0.3114],
        [0.7385, 0.7916, 0.4976, 0.8715],
        [0.0765, 0.3399, 0.0713, 0.7227],
        [0.2511, 0.9674, 0.1195, 0.0793]])


torch.float32

In [7]:
x_tensor=torch.rand(size=(224,224,3))
print(x_tensor)
x_tensor.ndim,x_tensor.shape

tensor([[[1.6294e-01, 6.3360e-05, 3.3415e-01],
         [6.8860e-01, 1.9463e-01, 3.1101e-01],
         [9.0508e-01, 4.8472e-01, 7.3141e-01],
         ...,
         [6.6275e-01, 7.6519e-01, 3.2688e-01],
         [1.6971e-01, 7.9300e-01, 8.7505e-01],
         [5.5660e-01, 5.1447e-01, 7.9754e-01]],

        [[6.0304e-01, 3.2364e-01, 9.0666e-01],
         [6.6578e-01, 4.6697e-01, 7.9836e-02],
         [8.1049e-01, 9.2476e-01, 7.5208e-02],
         ...,
         [8.0837e-01, 3.6587e-02, 4.6185e-02],
         [5.1892e-02, 9.1781e-01, 1.3359e-01],
         [3.5650e-01, 5.3492e-02, 7.6029e-01]],

        [[6.2714e-01, 7.4217e-01, 6.5473e-01],
         [7.2398e-02, 4.2418e-01, 8.4882e-01],
         [5.5489e-02, 7.0976e-01, 3.7296e-01],
         ...,
         [5.0691e-01, 8.7747e-01, 9.0554e-01],
         [9.5116e-01, 9.0753e-01, 8.4814e-01],
         [6.4040e-01, 7.4605e-02, 4.9156e-01]],

        ...,

        [[6.0411e-01, 7.3274e-01, 8.6345e-01],
         [9.1945e-01, 6.3198e-01, 9.9517e-01]

(3, torch.Size([224, 224, 3]))

In [8]:
#tensor of zeros
zeros=torch.zeros(size=(2,3,4))
zeros,zeros.shape,zeros.dtype,zeros.ndim

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([2, 3, 4]),
 torch.float32,
 3)

In [9]:
#tensor of ones
ones=torch.ones(size=(2,3,4))
ones,ones.shape,ones.dtype,ones.ndim

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 3, 4]),
 torch.float32,
 3)

In [10]:
#arrange
t_tensor=torch.arange(start=0,end=10,step=2)#can write it as (0,10,2)
t_tensor

tensor([0, 2, 4, 6, 8])

In [11]:
r_tensor=torch.tensor(data=[5,9,6],
                      device='cpu',#default none i can here use cpu or gpu, if i want to use gpu write cuda
                      requires_grad=True,#flag true or false,if true its mean store the operations on this tensor ,useful in BackPropagation that update weights ,default equal false
                      dtype=torch.float32
                      )
r_tensor,r_tensor.dtype,r_tensor.device,r_tensor.requires_grad

(tensor([5., 9., 6.], requires_grad=True),
 torch.float32,
 device(type='cpu'),
 True)

Tensor Operations

1-multpliy

2-addition

3-division

4-subtraction


In [12]:
x=torch.rand(size=(3,3))
x

tensor([[0.9475, 0.0758, 0.8291],
        [0.6449, 0.6956, 0.8285],
        [0.9094, 0.3054, 0.6041]])

In [13]:
x=x+12
x

tensor([[12.9475, 12.0758, 12.8291],
        [12.6449, 12.6956, 12.8285],
        [12.9094, 12.3054, 12.6041]])

In [14]:
x=x-2
x

tensor([[10.9475, 10.0758, 10.8291],
        [10.6449, 10.6956, 10.8285],
        [10.9094, 10.3054, 10.6041]])

In [15]:
x=x*2
x

tensor([[21.8951, 20.1516, 21.6582],
        [21.2898, 21.3913, 21.6569],
        [21.8188, 20.6109, 21.2082]])

In [16]:
x=x/3
x

tensor([[7.2984, 6.7172, 7.2194],
        [7.0966, 7.1304, 7.2190],
        [7.2729, 6.8703, 7.0694]])

In [17]:
y=x*x
y

tensor([[53.2660, 45.1209, 52.1198],
        [50.3616, 50.8430, 52.1135],
        [52.8954, 47.2009, 49.9763]])

In [18]:
x=torch.multiply(x,x)
x

tensor([[53.2660, 45.1209, 52.1198],
        [50.3616, 50.8430, 52.1135],
        [52.8954, 47.2009, 49.9763]])

In [19]:
z=torch.rand(size=(3,1))
z

tensor([[0.3066],
        [0.3469],
        [0.5475]])

In [20]:
f=torch.matmul(x,z)
f

tensor([[60.5215],
        [61.6124],
        [59.9557]])

In [21]:
#manual seed generation
torch.manual_seed(42)#in function rand uf i run a multoile time the numbers in tensor will change but if use manual seed it will br the same numbers whatever how many times i run
random=torch.rand(size=(3,3))
random


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [22]:
from torch import nn
linear=nn.Linear(in_features=7,out_features=7)
l=torch.rand(size=(4,7))
u=linear(l)
u


tensor([[ 0.7051, -0.2982, -0.4677, -0.1081,  0.6268, -0.5662,  0.0187],
        [ 0.1833, -0.1319, -0.0342,  0.2409,  0.7545, -0.3065,  0.0655],
        [ 0.4877, -0.0887, -0.1096,  0.2450,  0.6908, -0.1542,  0.1849],
        [ 0.3705, -0.2586, -0.3475,  0.1475,  0.6644, -0.1468,  0.2507]],
       grad_fn=<AddmmBackward0>)

In [23]:
v=torch.arange(0,10)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
v.min(),v.max(),v.type(torch.float32).mean()

(tensor(0), tensor(9), tensor(4.5000))

In [25]:
v.argmin(),v.argmax()#return index of max and min

(tensor(0), tensor(9))

In [26]:
float_tensor=torch.arange(0,10)
float_tensor,float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [27]:
float_tensor=torch.arange(0,10,1.)
float_tensor,float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)