In [1]:
import torch

In [2]:
scaler=torch.tensor(6)
scaler,scaler.ndim,scaler.item() #ndim is a build in function in pytorch return tensor's dimension


(tensor(6), 0, 6)

In [3]:
#create vector of tensor
vector=torch.tensor([1,2])
vector,vector.ndim,vector.shape #item run in scaler only

(tensor([1, 2]), 1, torch.Size([2]))

In [4]:
#matrix
matrix=torch.tensor([[1,2],[3,4]])
matrix,matrix.shape,matrix.ndim

(tensor([[1, 2],
         [3, 4]]),
 torch.Size([2, 2]),
 2)

In [5]:
#higher order dimension
d3_tensor=torch.tensor([[[1,2,3],
 [4,5,6],
  [7,8,9]]])
d3_tensor,d3_tensor.shape,d3_tensor.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [6]:
#create a random tensor
random_tensor=torch.rand(size=(4,4))
print(random_tensor)
random_tensor.dtype

tensor([[0.4491, 0.7848, 0.8829, 0.9892],
        [0.8263, 0.7406, 0.6080, 0.2834],
        [0.5470, 0.8587, 0.8301, 0.0703],
        [0.3639, 0.5213, 0.6541, 0.1239]])


torch.float32

In [7]:
x_tensor=torch.rand(size=(224,224,3))
print(x_tensor)
x_tensor.ndim,x_tensor.shape

tensor([[[0.2090, 0.2911, 0.5754],
         [0.1703, 0.0804, 0.9721],
         [0.4274, 0.3039, 0.7628],
         ...,
         [0.0987, 0.8868, 0.6834],
         [0.4566, 0.5667, 0.7233],
         [0.4133, 0.4523, 0.3159]],

        [[0.9495, 0.9838, 0.7480],
         [0.1350, 0.5744, 0.1886],
         [0.8634, 0.4249, 0.7848],
         ...,
         [0.5210, 0.8799, 0.0906],
         [0.2659, 0.5506, 0.1600],
         [0.7041, 0.4435, 0.9547]],

        [[0.7021, 0.1068, 0.0294],
         [0.9704, 0.3421, 0.1198],
         [0.7723, 0.0601, 0.6548],
         ...,
         [0.7593, 0.7158, 0.0737],
         [0.5389, 0.7228, 0.7839],
         [0.8319, 0.0593, 0.5532]],

        ...,

        [[0.2877, 0.3564, 0.8620],
         [0.3589, 0.0533, 0.1167],
         [0.4393, 0.7465, 0.2785],
         ...,
         [0.7569, 0.1252, 0.7130],
         [0.5451, 0.9749, 0.7728],
         [0.5899, 0.1425, 0.8262]],

        [[0.0845, 0.0818, 0.5099],
         [0.0422, 0.5243, 0.3999],
         [0.

(3, torch.Size([224, 224, 3]))

In [8]:
#tensor of zeros
zeros=torch.zeros(size=(2,3,4))
zeros,zeros.shape,zeros.dtype,zeros.ndim

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([2, 3, 4]),
 torch.float32,
 3)

In [9]:
#tensor of ones
ones=torch.ones(size=(2,3,4))
ones,ones.shape,ones.dtype,ones.ndim

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 3, 4]),
 torch.float32,
 3)

In [10]:
#arrange
t_tensor=torch.arange(start=0,end=10,step=2)#can write it as (0,10,2)
t_tensor

tensor([0, 2, 4, 6, 8])

In [11]:
r_tensor=torch.tensor(data=[5,9,6],
                      device='cpu',#default none i can here use cpu or gpu, if i want to use gpu write cuda
                      requires_grad=True,#flag true or false,if true its mean store the operations on this tensor ,useful in BackPropagation that update weights ,default equal false
                      dtype=torch.float32
                      )
r_tensor,r_tensor.dtype,r_tensor.device,r_tensor.requires_grad

(tensor([5., 9., 6.], requires_grad=True),
 torch.float32,
 device(type='cpu'),
 True)

Tensor Operations

1-multpliy

2-addition

3-division

4-subtraction


In [12]:
x=torch.rand(size=(3,3))
x

tensor([[0.6303, 0.0615, 0.2170],
        [0.4568, 0.7218, 0.6054],
        [0.0946, 0.9219, 0.0761]])

In [13]:
x=x+12
x

tensor([[12.6303, 12.0615, 12.2170],
        [12.4568, 12.7218, 12.6054],
        [12.0946, 12.9219, 12.0761]])

In [14]:
x=x-2
x

tensor([[10.6303, 10.0615, 10.2170],
        [10.4568, 10.7218, 10.6054],
        [10.0946, 10.9219, 10.0761]])

In [15]:
x=x*2
x

tensor([[21.2606, 20.1231, 20.4339],
        [20.9137, 21.4436, 21.2107],
        [20.1892, 21.8437, 20.1523]])

In [16]:
x=x/3
x

tensor([[7.0869, 6.7077, 6.8113],
        [6.9712, 7.1479, 7.0702],
        [6.7297, 7.2812, 6.7174]])

In [17]:
y=x*x
y

tensor([[50.2238, 44.9931, 46.3938],
        [48.5980, 51.0920, 49.9884],
        [45.2892, 53.0166, 45.1237]])

In [18]:
x=torch.multiply(x,x)
x

tensor([[50.2238, 44.9931, 46.3938],
        [48.5980, 51.0920, 49.9884],
        [45.2892, 53.0166, 45.1237]])

In [19]:
z=torch.rand(size=(3,1))
z

tensor([[0.4280],
        [0.3011],
        [0.1931]])

In [20]:
f=torch.matmul(x,z)
f

tensor([[44.0017],
        [45.8366],
        [44.0607]])

In [21]:
#manual seed generation
torch.manual_seed(42)#in function rand uf i run a multoile time the numbers in tensor will change but if use manual seed it will br the same numbers whatever how many times i run
random=torch.rand(size=(3,3))
random


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [22]:
from torch import nn
linear=nn.Linear(in_features=7,out_features=7)
l=torch.rand(size=(4,7))
u=linear(l)
u


tensor([[ 0.7051, -0.2982, -0.4677, -0.1081,  0.6268, -0.5662,  0.0187],
        [ 0.1833, -0.1319, -0.0342,  0.2409,  0.7545, -0.3065,  0.0655],
        [ 0.4877, -0.0887, -0.1096,  0.2450,  0.6908, -0.1542,  0.1849],
        [ 0.3705, -0.2586, -0.3475,  0.1475,  0.6644, -0.1468,  0.2507]],
       grad_fn=<AddmmBackward0>)

In [23]:
v=torch.arange(0,10)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
v.min(),v.max(),v.type(torch.float32).mean()

(tensor(0), tensor(9), tensor(4.5000))

In [25]:
v.argmin(),v.argmax()#return index of max and min

(tensor(0), tensor(9))

In [26]:
float_tensor=torch.arange(0,10)
float_tensor,float_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [27]:
float_tensor=torch.arange(0,10,1.)
float_tensor,float_tensor.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [30]:
#Transpose
print(u.shape)
print(u.T)
u_transpose=torch.transpose(u,0,1)
print(u_transpose.shape)

torch.Size([4, 7])
tensor([[ 0.7051,  0.1833,  0.4877,  0.3705],
        [-0.2982, -0.1319, -0.0887, -0.2586],
        [-0.4677, -0.0342, -0.1096, -0.3475],
        [-0.1081,  0.2409,  0.2450,  0.1475],
        [ 0.6268,  0.7545,  0.6908,  0.6644],
        [-0.5662, -0.3065, -0.1542, -0.1468],
        [ 0.0187,  0.0655,  0.1849,  0.2507]], grad_fn=<PermuteBackward0>)
torch.Size([7, 4])


In [33]:
#another way to transpose
u_transpose2=u.t()
print(u.shape)
print(u_transpose2.shape)

torch.Size([4, 7])
torch.Size([7, 4])


In [43]:
#mean
mean1=torch.arange(0,100.,10)
print(mean1)
print(mean1.dtype)
print(mean1.mean())

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
torch.float32
tensor(45.)


In [46]:
#convert int into float
mean2=torch.arange(0,10,1)
mean2=mean2.type(torch.float32)
print(mean2)
print(mean2.dtype)
print(mean2.mean())

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32
tensor(4.5000)


In [56]:
#Reshaping a tensor
re=torch.rand(size=(540,240,3))
re=re.reshape(240,540,3)
re.shape #it have to be the same size if i have image and total of pixels 17000 when i reshape it have to be the same pixels

torch.Size([240, 540, 3])

If i have image i can resize it using

resized=transformrs.Resize((340,340))

In [59]:
print(mean2.shape)
mean2=mean2.reshape(1,-1)#1 to add a dimension
print(mean2.shape)
mean2=mean2.reshape(1,1,-1)
mean2.shape

torch.Size([1, 10])
torch.Size([1, 10])


torch.Size([1, 1, 10])

Shapes important bec it is a common error in pytorch when i deal with tensors


In [60]:
float_tensor=mean2.reshape(2,5)
float_tensor

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [67]:
# i have image or tensor 224,224,3 and i want to compress it into vector
o=torch.rand(size=(224,224,3))
o=o.reshape(224*224,3)
print(o.shape)
o=o.reshape(224*224*3)
print(o.shape)
o=o.reshape(-1,1)
print(o.shape)

torch.Size([50176, 3])
torch.Size([150528])
torch.Size([150528, 1])


In [69]:
x

tensor([[50.2238, 44.9931, 46.3938],
        [48.5980, 51.0920, 49.9884],
        [45.2892, 53.0166, 45.1237]])

In [74]:
#stack tensor
x_stack=torch.stack([x,x,x,x])
x_stack,x_stack.shape

(tensor([[[50.2238, 44.9931, 46.3938],
          [48.5980, 51.0920, 49.9884],
          [45.2892, 53.0166, 45.1237]],
 
         [[50.2238, 44.9931, 46.3938],
          [48.5980, 51.0920, 49.9884],
          [45.2892, 53.0166, 45.1237]],
 
         [[50.2238, 44.9931, 46.3938],
          [48.5980, 51.0920, 49.9884],
          [45.2892, 53.0166, 45.1237]],
 
         [[50.2238, 44.9931, 46.3938],
          [48.5980, 51.0920, 49.9884],
          [45.2892, 53.0166, 45.1237]]]),
 torch.Size([4, 3, 3]))

In [83]:
k=torch.arange(0,10)
k=k.reshape(1,-1)
print(k.shape)
k=k.squeeze() #squeeze remove extra dimension
print(k.shape)
k=k.unsqueeze(dim=0) #add dimension where i put in any dim
print(k.shape)
k=k.unsqueeze(dim=2)
print(k.shape)
print(k)

torch.Size([1, 10])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1, 10, 1])
tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])


In [87]:
#permute
#if i have tensor(10.20,1) and want to cnovert it into (1,10,20)
p=torch.rand(224,260,3)
print(p.shape)
p=p.permute(2,0,1)
print(p.shape)

torch.Size([224, 260, 3])
torch.Size([3, 224, 260])
